### ISSUE TITLE
Migrating issues from Bitbucket?

### ISSUE THREAD

**Issue by grojguy** [zserge/jsmn-broken-issues#1]
Hello, 

I have opened several issues in the Bitbucket jsmn repo.  Would you like me to re-open those same issues here on github?   Or do you plan to migrate all the open Bitbucket issues?

Thank you

**Comment by zserge** [comment]
Honestly, I don't know yet. I prefer to move everything from bitbucket, but
as I understand the pull requests can't be moved? If your issues were not
linked to the pull requests - may I suggest you to wait for another couple
of days to let me move the issues automatically, and if not - add them
manually?

I'm sorry, I really want to keep jsmn alive, but I don't have much time
these days.

**Comment by grojguy** [comment]
Thanks for the answer Serge.  Yes, I completely understand the issue of limited time.  I would like to contribute and help fix those few issues, but I am barely staying alive with my current workload.  I will still try my best to give those issues a look though.  
I will wait until you move the requests then.  
Thanks again for jsmn.  It's a super-slick approach. I'm using it in a Microchip MCU embedded device in a JSON API parser.  I love the approach of in-place tokenizing.  It's perfectly simple and lightweight. 
-Matthew

**Comment by zserge** [comment]
Ok. I got some news, both good and bad.

Good - I've finally moved all my issues from Bitbucket to Github using a migration script.

Bad - I've messed up this repository, so I'm going to close it soon. The migration script has been broken - it didn't handle unicode at all and didn't skip previously uploaded issues. So this repo is now filled with duplicated issues and is useless now. Instead - please watch/star/fork the new `zserge/jsmn` repo (as you can see this repo is now renamed to jsmn-broken-issues). The new repo contains all the code and all the issues, so pull requests are welcome!
